<?php

$pageIntros = array(
	"savannah" => array(
		"You get on top of the car to have a nice view from the roof on this sea of yellow grass. The savannah is really an amazing landscape.",
		"The car drives fast on the dusty road as you look at the horizon trying to spot something in the grass.",
		"The high grass is really difficult for spotting animals as they can hide easily but you still look through the window as far as you can.",
		"Robert drives and you keep an eye on the grassland with your binoculars in hand to be sure not to miss anything!",
		"The bush around the road are quite thick but you look through the window attentively in order to find a moving target.",
		"The car moves near the bushes, you try to look closely into them without getting hurt by the spines at the window.",
		"Nothing but yellow grass and blue sky at the horizon, that is the landscape you were expecting by coming here.",
		"Only acacias can stand alone in this wide open grassland and be seen from so far away.",
		"You see some small bumps in the savannah but as soon as the car gets closer you notice they're just termite nests.",
		"Termite nests in the high yellow grass are really tricking you, you thought you spotted a big game...",
		"The savannah is dominated by the grass but some big fig trees stand high in the back to complete the landscape.",
		"Among the many amazing things you see in the savannah, the shapes of the cactus are really something.",
		"These cactus in the middle of the open grassland look like vegetation from another planet.",
		"Robert is trying to move slowly through the damaged road as you look through the car at this ocean of grass.",
		"Neverending savannah on the horizon, some trees, the blue sky, and nothing else but your hope of spotting a nice game.",
		"Some birds are flying in round above the yellow hill, maybe something is hidden in the high grass.",
		"It's almost impossible to see anything inside these bushes, even though Robert drives slowly.",
		"The bushes are high and dense so anything could be hidden there while the car passes just next to it...",
		"You can't help but look at the branches of these big acacias with the hope of spotting a leopard.",
		"These fig trees are sometimes used as a home by birds and even mammals but you don't see anything from here.",
		"Some of the cactus in the savannah reach very high, but it's almost the only trees you can see there.",
		"Many palm trees and an ocean of grass, that's all you see, so where are all the animals?",
		"You were hoping to see many animals in this wide open grassland but so far it's just cactus and termite nests..."
		),
	"water" => array(
		"You approach the riverside where many animals would come to have a drink or get a small bath, you wish you could do the same now.",
		"The road along the river is beautiful, in between the savannah, the forest and the water!",
		"The river is quite large and you can see from here that it goes pretty far down the park and through the forest.",
		"Some foam floats on the river, there must be a waterfall near here that produced these.",
		"Many flowers and even some grass are floating on the river, it's so strange as it moves.",
		"The riverside hides a lot of bird nests, Robert sure knows them all by heart and could talk about them for hours.",
		"It would be interesting to see the hierarchy of access to water on the shore, Robert tells you that elephants are always first.",
		"Robert drives the car a bit fast in order to reach the river for the bath time of many animals!",
		"The river is a bit large so it's difficult to spot animals on the other side.",
		"From the shore, you can see a dense forest on the other side of the river but spotting animals will be difficult.",
		"Nothing but a river surrounded by forests on both sides, animals should be near.",
		"There is a lake further on the horizon where the river passes, it is quite a landscape from here!",
		"The water and the sky have the exact same colour and you're not exactly sure if the birds on top are swimming or not...",
		"Next to the river you feel the wind in your hair, it was the perfect time to come here and get fresh air.",
		"From here, the river looks infinite, it goes so far that you can't see where its path ends.",
		"The vegetation around the water is really different, you spotted so many nenuphars and papyrus!",
		"The papyrus are covering almost all the shore, it's the home of so many birds.",
		"You're not sure if these things moving on the water are vegetation or animals but they look strange.",
		"Unfortunately, the safari doesn't include a diving tour as it would be surely interesting to see the aquatic fauna of the park.",
		"There must be so many fishes and amphibians living in these waters, but sadly no chance to see them today.",
		"Seeing animals from the shore can be really hard as the river is large and the forest on the other side is thick.",
		"There're always many animals around water places, you just need to spot them from the shore.",
		"The best place to have a good view of the animals near the river would be on top of this hill on the other side."
		),
	"forest" => array(
		"You stay inside the car as the trees are surrounding the road are quite low and could scratch you.",
		"You enter the dense forest slowly with the car but soon you can't even see the place you left behind.",
		"The forest is darker than the rest of the area because of the density of trees but some sunlight still passes through the leafs.",
		"The light filtered through the trees is incredible, but it's also the worst to take pictures...",
		"The humidity and the sun makes this whole forest foggy, sometimes you can't even see a few meters away.",
		"The road is really narrow to access the forest through the low trees, it's a strange atmosphere.",
		"Nothing but trees, of course, it's a forest, but you were expecting a bit more diversity.",
		"The neverending greenness of this place is unique, and you're not even lost in between the trees, you're in the car!",
		"The car struggles a bit to enter the tropical rainforest but it's already an amazing landscape from here.",
		"Robert says that you'll just be passing next to the forest as entering it would be too complicated with the car.",
		"You're in the tropical rainforest, fortunately it's not the rain season, but you still feel a lot of humidity in this place.",
		"The trees are breathing and releasing a lot of water which makes the forest a very humid place, it's not unpleasant though.",
		"The sun is very high already so it's good to go hide under the trees and in the freshness of the forest.",
		"Many animals come to the forest once the morning passed to enjoy the shadow and the water it offers.",
		"You see through the window of the car all the surroundings of the forest full of bushes and small trees.",
		"It's difficult to spot animals in this dense forest, but you trust Robert and his expert eye.",
		"Binoculars are quite useless in the forest as long as the car moves, it's impossible to have a long distance view of anything.",
		"Unfortunately the car can't go further in the trees, it would have been nice to make a treck in this tropical forest.",
		"You're lucky there's no car coming the other way because the forest road is too narrow to let two cars pass at the same time.",
		"The trees are so dense and so big that you look above the car but you can't see the sky clearly anymore.",
		"You hear many different sounds coming from the trees, the wind of course, some birds too, but other unidentified sounds also.",
		"Fortunately you entered the forest during the day because seeing how dark and compact it is, it would be a nightmare at night.",
		"It's so bad that you can't leave the car nor the road, there should be incredible animals to spot inside the forest itself."
		),
	"building" => array("The sun is setting on the horizon while you're approaching the checkpoint. This day has been full of marvelous encounters.") // ending only
	);

$animalIntros = array(
	"This is the {animal}.",
	"Oh, it's the {animal}!",
	"Hm, look, this is a {animal}.",
	"Can you see it? The {animal}, just there.",
	"It's far away but I think it is the {animal}.",
	"Do you hear it? That's the {animal}.",
	"Did you see it? It was the {animal}.",
	"Amazing! The {animal}!",
	"You're lucky, it's a {animal}.",
	"I didn't see it for a long time, the {animal}!",
	"Last time I couldn't see it, it's the {animal}.",
	"I'm always happy to see the {animal}.",
	"Look at this {animal}, beautiful!",
	"This is nature's work: the {animal}.",
	"I present you the {animal}.",
	"Shhh... Don't make a sound, it's the {animal}.",
	"Oh, let's come closer... Look, it's the {animal}.",
	"Do you have your camera? Look there, it's the {animal}.",
	"I can see it in my binoculars, it's the {animal}.",
	"Can you see it in your binoculars? The {animal}.",
	"Do you have it on camera? It's the {animal}.",
	"Take your binoculars, there's the {animal}!",
	"Take your camera, it's the {animal}!",
	"Be careful, it could go away, it's the {animal}.",
	"Be silent, just observe, it's the {animal}.",
	"If you look on the right you'll see it, the {animal}.",
	"You can see the {animal} on the left.",
	"Look a bit more to the right, you see the {animal}?",
	"It's the {animal} in front of us!",
	"The {animal} is in the back, do you see it?",
	"Did you recognize the {animal}? It's just there.",
	"The {animal} didn't see us yet, but you see it right?",
	"The {animal}, a truly interesting animal.",
	"It's technical name is the {animal}.",
	"There, on the ground, the {animal}!",
	"Wow, look at this {animal}!",
	"This is our lucky day, we just saw the {animal}!",
	"I introduce you the {animal}.",
	"I'm sure you know this one, the {animal}.",
	"This is the {animal}, pretty famous, isn't it?",
	"The {animal}, beautiful right?",
	"Oh, the {animal}, I can tell you some things about it.",
	"The {animal}! I know a bit about it.",
	"I will tell you more about this one, the {animal}.",
	"Like always, I know this one too, the {animal}!",
	"This {animal} would win a beauty contest for sure!",
	"This {animal} is the best.",
	"This one is one of my favourite, the {animal}!",
	"I really like this one, the {animal}.",
	"I like how this {animal} looks.",
	"The style of this {animal} is impressive.",
	"This {animal} has so much grace!"
	);

$sameAnimal = array(
	"Oh, just another {animal}.",
	"The {animal}, again.",
	"We've alreay seen that {animal}.",
	"It's just the {animal}.",
	"Nothing new, the {animal}.",
	"So many {animal} today!",
	"Did we come back to see this {animal} again?",
	"One more {animal}.",
	"I don't mind seeing this {animal} again.",
	"How many times have we seen this {animal}?",
	"We've seen this {animal} twice now, or more?"
	);

$sectionTransitions = array(
	"Also",
	"I can also tell you this",
	"If you want to know more",
	"Additionnaly",
	"Furthermore",
	"Moreover",
	"In case you didn't know",
	"Just so you know",
	"I may be too precise but",
	"I can tell you a bit more",
	"What I can also say",
	"You must also know",
	"It's good to know also",
	"Interesting fact",
	"You might not know",
	"More about this animal",
	"But there's more",
	"I can say a bit more about it",
	"I know some more",
	"I can also tell you this",
	"This might sound too precise",
	"I don't want to sound too scientific",
	"I want to keep it simple",
	"I'm trying to be exhaustive",
	"I'll tell you what I know",
	"I'll tell you what you need to know",
	"Fascinating thing",
	"Funny thing is", 
	"Interesting animal",
	"Peculiar species"
	);

$verbTalking = array(
	"says",
	"tells",
	"explains",
	"continues",
	"adds",
	"declares",
	"mentions",
	"suggests",
	"affirms",
	"remarks",
	"informs",
	"describes",
	"narrates"
	);

$pageNext = array(
	"savannah" => array(
		"You see some fresh footprints on the road towards going further into the savannah, let's have a look at it.",
		"Robert recognizes a fresh footprint on the ground going forward and to the bushes. Let's follow it!",
		"Some fresh animal poo lies on the road and there's more of it further next to the bush there, you'll follow the poo!",
		"Robert points towards a thing on the ground next to the grass. It's poo! You decide to follow it.",
		"The road on the left leads you to the open savannah, you want to see what's hidden in this grass.",
		"The road forward is surrounded by bushes where animals might hide. Let's see...",
		"Keep going forward to reach the acacias where animals might look for shadow.",
		"On the left, you see big fig trees that might be the perfect place for animals to chill. Let's chill there too!",
		"You recognize some individual trees in a sea of grass, the shadow would probably attract animals, let's see.",
		"Robert received a call from another ranger who told him to go this way in the savannah, so let's do that.",
		"A car just passed next to yours and the guide told Robert to go further in the grassland, it's this way.",
		"A bus full of elderly tourists happens to come your way, they tell you that they saw some nice stuff in the bushes there.",
		"Something moved in the horizon, it's maybe hidden in the grass now, let's come closer.",
		"The bush there just moved, you can swear it although Robert doesn't believe you. Let's see!",
		"A strange sound came from the left, from the plains, let's see.",
		"There's a silhouette far away in the open grass area, you want to have a closer look.",
		"Robert tells you that in the savannah back there he usually sees some interesting game, you decide to trust him.",
		"Robert saw something in the grass there, let's see.",
		"Robert remembers that he saw some big game around these bushes, let's try your chance.",
		"A sign says that this way is the open savannah, OK let's try that.",
		"This road leads closer to the open grass area, you decide to go this way.",
		"Up on the hill, among the grass, something moved. Let's go up there.",
		"There's a bush on the top of that road, it might be interesting to have a look."
		),
	"water" => array(
		"It's the perfect time for animals to have some fresh water, let's see what's on the shore.",
		"The shore is usually an attractive place for animals of any kind, let's go there.",
		"The road on the right leads to the river. Let's go.",
		"The lake and river area is full of interesing animals at this time of the day, you decide to go there.",
		"Last time, Robert saw some interesting game on the riverside. Let's see.",
		"A ranger just called Robert and told him to look next to the water, follow this advice.",
		"You can see the river on this side of the road, let's take a look there.",
		"There's a lake not so far away, maybe you can see some nice animals.",
		"The sign says the river is this way, let's try that.",
		"The sound of the waterfall comes to your ear and you want to know what animals you can see there.",
		"There's a river down there and some shapes moving, let's look at these animals!",
		"If you follow that road, you'll come to the shore, it's a good place for animal sighting.",
		"When the animals don't find shadow, they usually go for water, so let's try that.",
		"You decide to go east, towards the river where animals go to drink.",
		"A lake is hidden behind this hill, let's have a look at this landscape!",
		"There's a lake and a river if you go down this road, it should make a nice view.",
		"Some cars are gathered around the lake down there, there should be something nice to see.",
		"Water places are filled with a high diversity of animals, you decide to look at that.",
		"Robert knows that this time of the day, animals tend to look for water, so you go this way.",
		"There's a road that follows the river, let's have a look around there.",
		"Some footprints go towards the shore, the animals should be there drinking, let's see.",
		"There's some poo on this road that leads to the water, you want to know which animal makes this kind of feces.",
		"Another safari car is coming your way from the road that goes to the river, let's see what they've seen!"
		),
	"forest" => array(
		"The forest makes a very good place for animals to hide from the sun, you decide to look for them there.",
		"There's a dense tropical forest this way, it's a home to many nice animals so let's check there.",
		"You see some footprints on the ground that seem to enter the forest, let's follow this.",
		"There's a pile of poo on the side of the forest, let's enter to find this animal.",
		"The leaves just moved in the forest and you're pretty sure it's not the wind. Let's dive into it.",
		"The sound of branches cracking came to Robert's ear, there should be some interesting animals in this forest, let's see.",
		"The south road goes deep into the tropical rainforest but you're not afraid and go there.",
		"The west road is full of compact trees, but you want to have a look there.",
		"Going north brings you to the great tropical forest, and you want to scratch the surface of it.",
		"The sign on the side of the road says that the forest is this way. OK, let's try.",
		"The hill in front of you is full of dense trees, let's go up there.",
		"Below this road, you can't see nothing but trees and trees, you want to jump right into that.",
		"Robert just called a ranger who told him to look into the forest, you follow his advice.",
		"Robert tells you that this forest is home to some great animals, let's see that.",
		"You saw something in the trees back there, let's have a look.",
		"When the sun is hot like today, animals go in the shadow of the forest, let's do like them.",
		"It's very hot right now and the rainforest looks like the best place to get some fresh air.",
		"You can see a car entering the forest on the horizon, let's follow them.",
		"There's a tropical rainforest in the north. You decide to go this way.",
		"The forest is as much part of the safari as the savannah, let's have a closer look at it.",
		"The road there passes through a dense tropical forest, let's enter it.",
		"Many thick trees are aligned along this road, let's drive next to them and try to see something.",
		"The forest on the side looks a bit dark and cold but it might also be the perfect time and place for animals so let's try it."
		),
	"building" => array("There's a checkpoint ahead...") // ending only
	);

?>